services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - postgres
    command: [ "-path", "/migration", "-database", "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up" ]
    volumes:
      - ./migration:/migration

  obfs-detector:
   build: .
   container_name: obfs-detector
   depends_on:
     - postgres
     - migrate
